version: '3.6'
services:
  traefik:
    image: traefik
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - mynet
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
      - ./acme.json:/acme.json # chmod 600 acme.json
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    command: --api
  main:
      image: nginx
      networks:
        - mynet
      deploy:
        replicas: 2
        resources:
          limits:
            cpus: "0.1"
            memory: 50M
        restart_policy:
          condition: on-failure
        labels:
          - "traefik.port=80"
          - "traefik.backend=main"
          - "traefik.frontend.rule=Host:liangyouapp.com"
  two:
      image: jwilder/whoami
      networks:
        - mynet
      deploy:
        replicas: 2
        resources:
          limits:
            cpus: "0.1"
            memory: 50M
        restart_policy:
          condition: on-failure      
        labels:
          - "traefik.port=8000"
          - "traefik.backend=two"
          - "traefik.frontend.rule=Host:two.liangyouapp.com"
  three:
      image: emilevauge/whoami
      networks:
        - mynet
      deploy:
        replicas: 2
        resources:
          limits:
            cpus: "0.1"
            memory: 50M
        restart_policy:
          condition: on-failure      
        labels:
          - "traefik.port=80"
          - "traefik.backend=three"
          - "traefik.frontend.rule=Host:three.liangyouapp.com"
networks:
  mynet:
    driver: overlay
