debug = false
logLevel = "ERROR"
defaultEntryPoints = ["https", "http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

[acme]
  email="510830568@qq.com"
  storage = "/etc/traefik/acme.json"
  entryPoint = "https"
  onHostRule = true
[acme.httpChallenge]
  entryPoint="http"

[docker]
  endpoint="unix:///var/run/docker.sock"
  domain = "liangyoult.com"
  exposedByDefault=false
  watch=true
  swarmmode=true